### ISSUE TITLE
Build product API

### ISSUE THREAD

**Issue by Nitinkumar-Gove** [Nitinkumar-Gove/shopyst#14]
This API will interact with the vendor API to - 
1. search products based on given query 
2. pull product specific ratings
3. integrate with the vendor api

**Comment by Sagar-Mane** [comment]
1. Search products based on given query is done. Please review
sample request format - http://localhost:3000/findProducts?keywords=iphoneX&entriesPerPage=3

Add 'gaurangm-cmpe295-PRD-c786e1828-5f5dd874' to vendorsecret in config file before making request to api.
